generate_client_greeting:
  description: >
    Compose a professional and appreciative greeting for a client {recipient_name} on the occasion of {occasion}.
  expected_output: >
    A message showing gratitude and professionalism tailored to {recipient_name} for {occasion}.
  agent: client_greeting_agent
