generate_colleague_greeting::
  description: >
    Compose a professional and encouraging greeting for a colleague {recipient_name} on the occasion of {occasion}.
  expected_output: >
    A formal but friendly greeting message tailored to {recipient_name} for {occasion}.
  agent: colleague_greeting_agent
