generate_general_greeting:
  description: >
    Compose a general-purpose greeting message for {recipient_name} on the occasion of {occasion}.
  expected_output: >
    A well-crafted and thoughtful greeting tailored to {recipient_name} for {occasion}.
  agent: general_greeting_agent
