leads_information:
  description: >
    Find and provide information about the lead whose employee code is {employeeCode}.
  expected_output: >
    A detailed report containing the lead's name, job role, region, phone number, and email address.
  agent: lead_information_retriever_agent
